idf_component_register(
    SRCS
        "app_main.c"
        "../PeachAdminMessages/SerUtils.c"
        "../PeachAdminMessages/DeSerUtils.c"
        "../PeachAdminMessages/AdminMsgs.c"
        "../PeachAdminMessages/PeachMessages.c"
        "../PacketParser/EndPoints.c"
        "../PacketParser/MessageProcessing.c"
        "../PacketParser/PacketParser.c"
        "../PacketParser/PacketProcessor.c"
        "../PacketParser/PhysicalParams.c"
        "../PacketParser/SequenceMatcher.c"
        "../FileSystem/FileConfig.c"
        "../FileSystem/FileSystemSD.c"
        "../BasicGraph/BasicGraph.c"
        "../Hardware/Esp32/UartHW.c"
        "../SpiSlaveLink/SpiSlaveLink.c"
        "../DebugConsole/DebugConsole.c"
        "../WiFiManager/WiFiManager.c"
        "../OtaManager/OtaManager.c"
    INCLUDE_DIRS
        "."
        "../Display"
        "../PacketParser"
        "../FileSystem"
        "../BasicGraph"
        "../Hardware"
        "../Hardware/Esp32"
        "../PeachAdminMessages"
        "../SpiSlaveLink"
        "../DebugConsole"
        "../WiFiManager"
        "../OtaManager"
    REQUIRES
        LCD
        GUI
        fatfs
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        mqtt
        esp_https_ota
        esp_http_client
        console
        esp_lcd
        driver
)
